# Generated by Django 5.1.6 on 2025-02-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_auth_verified',
            field=models.BooleanField(default=False),
        ),
    ]
