# Generated by Django 5.1.6 on 2025-02-28 19:20

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='chart_timeframe',
            field=models.CharField(blank=True, default='D', max_length=10),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('text', 'Text Content'), ('video', 'Video Lesson'), ('interactive', 'Interactive Practice'), ('quiz', 'Quiz Assessment'), ('trading_practice', 'Trading Practice')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='practice_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='trading_pair',
            field=models.CharField(blank=True, default='eur/usd', max_length=20),
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent', models.DurationField(default=datetime.timedelta(0))),
                ('last_position', models.PositiveIntegerField(default=0)),
                ('practice_attempts', models.PositiveIntegerField(default=0)),
                ('practice_success', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
