# Generated by Django 5.1.6 on 2025-02-24 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_views_courseenrollment_webinarregistration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_level',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='courseprogress',
            old_name='user_course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='courseprogress',
            old_name='course_progress',
            new_name='progress',
        ),
        migrations.RenameField(
            model_name='courseprogress',
            old_name='course_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_title',
            new_name='title',
        ),
    ]
